language: java
before_install:
  - unset SORCER_HOME
  - export SORCER_HOME=`pwd`
  - echo "SORCER_HOME is $SORCER_HOME"
  - ifconfig
  - cat /etc/hosts
  - hostname
install: mvn -q -P disttest install
before_script:
#  - cp -f $SORCER_HOME/configs/template/sorcer.env_int-tests $SORCER_HOME/configs/sorcer.env
#  - export JAVA_OPTS=-Djava.net.preferIPv6Stack=true
  - cd distribution/target/sorcer-*/sorcer-*/
  - export SORCER_HOME=`pwd`
  - $SORCER_HOME/bin/sorcer-boot &
  - sleep 8
#temporally disable integration tests. Enable them after all of them has been migrated to sorcer-maven-plugin
#for now run locally:
#mvn verify -Dmaven.test.skip=false -Prun-its -pl :first-prv,:ju-arithmetic-prv
#script: cd $SORCER_HOME/sos/sos-tests/ && mvn -Dmaven.test.skip=false -Prun-its test
script: cd $SORCER_HOME/sos/sos-tests/ && mvn -Dmaven.test.skip=false test
jdk:
#  - openjdk6
#  - openjdk7
  - oraclejdk7
# whitelist
branches:
  only:
    - master

notifications:
  email:
    - sorcer-devel@lists.sourceforge.net
